INVESTMENT_TERMS = [
    # Funding rounds
    "seed",
    "pre-seed",
    "Series A",
    "Series B",
    "Series C",
    "Series D",
    "Series E",
    "growth round",
    "venture round",
    "bridge round",
    "IPO",
    "SPAC",
    "extension round",
    "convertible note",
    "SAFE",
    "late-stage round",
    "follow-on round",


    # Money language
    "raised",
    "raises",
    "funding",
    "backed by",
    "valuation",
    "valued at",
    "capital",
    "investment",
    "investors",
    "lead investor",
    "co-led",
    "participated",
    "announced funding",
    "closed a round",
    "secured funding",
    "secured financing",
    "fresh capital",
    "new funding",
    "venture-backed",
    "strategic investment",
    "oversubscribed round",
    "post-money valuation",
    "pre-money valuation",


    # M&A
    "acquired",
    "acquisition",
    "merger",
    "buyout",
    "strategic acquisition",
    "exit",
    "sold to",
    "take-private",
    "roll-up",

    #Startup_Creation
    "founded",
    "co-founded",
    "launches",
    "launching",
    "launched",
    "emerges",
    "stealth startup",
    "exits stealth",
    "spinout",
    "spin-off",
    "incubated",
    "accelerator",
    "demo day",
    "beta launch",
    "general availability",
    "GA release",
    "product launch",
    "introduced",
    "unveiled",
    "debuted",

    #Transaction_Signals
    "pilot program",
    "pilot project",
    "enterprise customer",
    "design partner",
    "customer adoption",
    "enterprise rollout",
    "signed customers",
    "signed contract",
    "signed deal",
    "contract award",
    "multi-year contract",
    "deployment",
    "production deployment",
    "implementation",
    "integration",
    "strategic partnership",
    "channel partner",
    "reseller agreement",
    "customer base",
    "renewal",
    "expansion deal",

    #Problem_signals
    "manual workflow",
    "manual review",
    "legacy software",
    "outdated system",
    "spreadsheet-driven",
    "paper-based workflow",
    "fragmented workflow",
    "fragmented vendor landscape",
    "inefficient process",
    "operational inefficiency",
    "process bottleneck",
    "lack of automation",
    "lack of visibility",
    "data silos",
    "data fragmentation",
    "staff shortage",
    "labor shortage",
    "backlog",
    "downtime",
    "error-prone",
    "compliance burden",
    "audit burden",
    "fraud risk",
    "claims leakage",
    "cost overruns",
    "supply chain disruption",

    #Regulatory_signals
    "regulatory requirement",
    "regulatory compliance",
    "new mandate",
    "compliance deadline",
    "reporting obligation",
    "policy reform",
    "legislative change",
    "sanctions regime",
    "export restriction",
    "export licensing",
    "data protection law",
    "privacy regulation",
    "carbon disclosure",
    "emissions reporting",
    "building code update",
    "safety regulation",
    "government procurement",
    "public sector mandate",
    "national security regulation",
    "critical infrastructure protection",

    #Sector_terms
    "agentic AI",
    "AI agent",
    "copilot software",
    "foundation model",
    "multimodal AI",
    "RAG",
    "AI orchestration",
    "model routing",
    "synthetic data",
    "data labeling",
    "inference infrastructure",
    "GPU cluster",
    "edge AI",
    "physical AI",
    "industrial AI",
    "autonomous systems",
    "computer vision platform",
    "robotics automation",
    "developer platform",
    "workflow automation",
    "enterprise platform",
    "vertical SaaS",
    "industry-specific software",
    "API platform",
    "data pipeline",
    "observability platform",
    "identity platform",
    "cyber resilience",
    "zero trust",

    #Venture_ecosystem_terms
    "portfolio company",
    "investment thesis",
    "new venture fund",
    "fund launch",
    "dry powder",
    "deal activity",
    "deal flow",
    "market opportunity",
    "high-growth sector",
    "booming sector",
    "next wave",
    "category leader",
    "market expansion",
    "consolidation trend",
    "industry transformation",

]