rss_sources = {
    "TechCrunch": "https://techcrunch.com/feed/",
    "Crunchbase News": "https://news.crunchbase.com/feed/",
    "VentureBeat": "https://venturebeat.com/feed/",
    "Sifted": "https://sifted.eu/feed",
    "CNBC": "https://www.cnbc.com/id/19854910/device/rss/rss.html",
    "PitchBook News": "https://pitchbook.com/news/feed",
    "Tech Funding News": "https://techfundingnews.com/feed/",
    "The Information": "https://www.theinformation.com/feed",
    "BetaKit": "https://betakit.com/feed/",
    "SiliconANGLE": "https://siliconangle.com/feed/",
    "The Next Web": "https://thenextweb.com/feed",
    "EU-Startups": "https://www.eu-startups.com/feed/",
    "StrictlyVC": "https://www.strictlyvc.com/feed/",
    "Axios Pro Rata": "https://www.axios.com/newsletters/pro-rata",
    "CB Insights": "https://www.cbinsights.com/research/feed/",
    "Andreessen Horowitz": "https://a16z.com/feed/",
    "Sequoia Capital": "https://www.sequoiacap.com/feed/",
    "Redpoint": "https://redpoint.com/feed/",
    "SemiAnalysis": "https://www.semianalysis.com/feed",
}