rss_sources = {
    "TechCrunch": "https://techcrunch.com/feed/",
    "Crunchbase News": "https://news.crunchbase.com/feed/",
    "VentureBeat": "https://venturebeat.com/feed/",
    "Sifted": "https://sifted.eu/feed",
    "Reuters": "https://www.reuters.com/business/rss",
    "CNBC": "https://www.cnbc.com/id/19854910/device/rss/rss.html",
    "PitchBook News": "https://pitchbook.com/news/feed",
    "Tech Funding News": "https://techfundingnews.com/feed/",
    "The Information": "https://www.theinformation.com/feed",
    "BetaKit": "https://betakit.com/feed/",
    "SiliconANGLE": "https://siliconangle.com/feed/",
    "The Next Web": "https://thenextweb.com/feed",
    "EU-Startups": "https://www.eu-startups.com/feed/",
    "StrictlyVC": "https://www.strictlyvc.com/feed/",
    "Axios Pro Rata": "https://www.axios.com/newsletters/pro-rata",
    "CB Insights": "https://www.cbinsights.com/research/feed/",
    "Andreessen Horowitz": "https://a16z.com/feed/",
    "Sequoia Capital": "https://www.sequoiacap.com/feed/",
    "Redpoint": "https://redpoint.com/feed/",
    "Exploding Topics": "https://explodingtopics.com/blog/rss.xml",
    "Product Hunt": "https://www.producthunt.com/feed",
    "Indie Hackers": "https://www.indiehackers.com/feed",
    "Hacker News": "https://news.ycombinator.com/rss",
    "SemiAnalysis": "https://www.semianalysis.com/feed",
    "MarkTechPost": "https://www.marktechpost.com/feed/",
}